name: Provision Kubernetes Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  create_infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_workspace: ${{ github.workspace }}/terraform
      TF_LOG: INFO
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/terraform
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE}}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-K8S-cluster

      - name: Checkout repository
        uses: actions/checkout@v1
 
      - name: Setup Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform
      
      - name: Install community.general collection and cloud.terraform
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install cloud.terraform

      - name: Terraform fmt
        id: fmt
        run: terraform fmt 

      - name: Terraform Init
        id: init
        run: terraform init 
          
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color 
      
      - name: Terraform Apply
        id: apply
        run: |
          terraform plan -no-color 
          terraform apply -auto-approve
      
      - name: Run The Playbook
        run: |
          ansible-playbook -i ../ansible/inventory.yml ../ansible/playbooks/cluster_init.yml 